### ISSUE TITLE
Brightness levels dim down to 0% and then back to previous settings

### ISSUE THREAD

**Issue by ElectricImpossible** [bbasil2012/SSLAC-ESP32#1]
Thank you for releasing this ESP32 firmware.

I am using build 2018-08-07 12:25:40 and occasionally I have a situation where all channels (currently using 5 PWM channels) will fade to 0% dimming then back to the brightness specified within 3seconds. This usually happens around four times a day.

The uptime on the ESP stays as expected.

Currently using Pins
32
25
26
27
14
23 (for a DS18b20)

I am using a PWM frequency of 10000 and non inverted.

Ideas?

**Comment by bbasil2012** [comment]
Hi, friend!
Thank you for using my software.
I have exactly the same issue.
All my channels work in an inverse mode, and  yours is not inverses.
Then I think that this is a software error.
I'll try to find it and fix it.

**Comment by bbasil2012** [comment]
@ElectricImpossible
Try it https://github.com/bbasil2012/SSLAC-ESP32/blob/master/betta/sslac-esp32-2018-10-19.zip

**Comment by bbasil2012** [comment]
I completed the testing.
The problem no longer manifests itself.
